# Generated by Django 4.2.7 on 2025-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mang', '0003_delete_passwordentry_alter_password_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='password',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
