# Generated by Django 4.2.7 on 2025-01-23 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mang', '0004_rename_site_name_password_name_password_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='password',
            name='url',
        ),
        migrations.AddField(
            model_name='password',
            name='logo',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
